### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by alessandroperilli** [jitcoder/lora-info#1]
This node is timely and extremely appreciated. There are other ways to get the LoRA keywords but a node that can be deployed anywhere is a more flexible option IMO. 

It works perfectly fine with all my LoRAs, except one: [Cartoon_SDXL_V2](https://civitai.com/models/140527?modelVersionId=155739).

When I select this lora, the node generates a halting error:

> File "xyz/ComfyUI/execution.py", line 153, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/execution.py", line 83, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/execution.py", line 76, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/custom_nodes/lora-info/lora_info.py", line 70, in lora_info
>     trainedWords = model_info.get("trainedWords")
>                    ^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'get'

I assume it cannot retrieve the appropriate information from Civitai and doesn't know how to ignore that situation. 

Ignoring would be better.

I have a couple of suggestions, so I'll open specific issues about them. Thank you!

**Comment by jitcoder** [comment]
good catch, will address shortly

**Comment by jitcoder** [comment]
addressed (https://github.com/jitcoder/lora-info/commit/6af244a4feba7db4af3c485fb0bb2a0312076901).

please run
```
git fetch
git pull
```
in the `custom-nodes/lora-info` directory

**Comment by alessandroperilli** [comment]
It works perfectly fine now, thank you. 

<img width="465" alt="Screenshot 2023-12-09 at 11 04 14" src="https://github.com/jitcoder/lora-info/assets/9775949/12300e47-4f18-4690-b7b9-1eb76919513c">

As a side note, tho, that LoRA exists on Civitai, per my linked original post.

I downloaded it from that link and I never changed its name.

**Comment by jitcoder** [comment]
> It works perfectly fine now, thank you.
> 
> <img alt="Screenshot 2023-12-09 at 11 04 14" width="465" src="https://private-user-images.githubusercontent.com/9775949/289267356-12300e47-4f18-4690-b7b9-1eb76919513c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjU4NjQsIm5iZiI6MTcwMjEyNTU2NCwicGF0aCI6Ii85Nzc1OTQ5LzI4OTI2NzM1Ni0xMjMwMGU0Ny00ZjE4LTQ2OTAtYjdiOS0xZWI3NjkxOTUxM2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMTIzOTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzg3NmI4ZmQ2M2JkODg4MTdhY2ZhMmZlNTBhOTY4ZDlkNzI5NzM4MjhkYjljN2Q2NThkMDJlZjg1NGVlNTVkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zMVpV3BqtZvn0VeA4yqfWLiynXxJRUxr0UmOqIgw8Xk">
> As a side note, tho, that LoRA exists on Civitai, per my linked original post.
> 
> I downloaded it from that link and I never changed its name.

hmm, it must be an issue on Civitai side. They might not have generated the hash of the model. The models in the node are pulled from Civitai using their `SHA256` hash.

In the future, once I'm more familiar with civitai's API, I'll add alternative methods to find a model if we fail to find it by hash
