### ISSUE TITLE
request an update to the lora info node.

### ISSUE THREAD

**Issue by msandroid** [jitcoder/lora-info#16]
![image](https://github.com/user-attachments/assets/a16c6494-c247-40f0-a736-823211e38564)
I would like to request an update to the 
lora info node.
Is it possible to have lona_ name as output?

**Comment by jitcoder** [comment]
hello!
sure this should be pretty straightforward to do. will let you know once its done. @Zakutu

**Comment by jitcoder** [comment]
https://github.com/jitcoder/lora-info/pull/17

feature has been added. please update the node.
note: after you update, you might need to re-create lora-info node in your workspaces if the output fields are messed up.
ie. `lora_name` output showing up as `example_prompt`
