### ISSUE TITLE
[FEATURE REQUEST] - Output triggers

### ISSUE THREAD

**Issue by alessandroperilli** [jitcoder/lora-info#2]
It would be great if the Lora Info node would be able to export just the trigger words (rather than the entire output) to an output pin. In that way, I could further manipulate and automatically insert them in other nodes. 

Thank you for considering my suggestion.

**Comment by jitcoder** [comment]
its a good idea, I think the node that I used as a reference to make this already does this: https://github.com/badjeff/comfyui_lora_tag_loader

I didn't play around with it much, but I think it does just that. my issue with it was that I wanted it to display info and examples etc. please do check the above out, if it doesn't work as expected, let me know and I'll add the feature into this

**Comment by alessandroperilli** [comment]
My suggestion does the reverse of what the `LoRA Tag Loader` does. I want to extract the trigger words from the `LoRA Info` dump and place them into an otherwise empty prompt node (or a debug node for logging purposes, etc.).

**Comment by jitcoder** [comment]
I see, let me see what I can do. (hopefully I understood everything correctly. this is day #2 with generative AI for me lol)

**Comment by alessandroperilli** [comment]
I know. I read your intro post on Reddit. I appreciate any time you'll dedicate to this request, if and when you'll feel comfortable with the complexities of the ComfyUI world. 
Even in its current form, the LoRA Info node is useful, and it's scheduled to be included in my upcoming [AP Workflow 6.1](https://perilli.com/ai/comfyui).

**Comment by jitcoder** [comment]
So it turns out I can't combine 'displaying' functionality and exporting values, so I created a sibling node that does the exporting.

<img width="854" alt="image" src="https://github.com/jitcoder/lora-info/assets/4588694/94586e1f-b28a-49d7-b056-afe2a1cea954">

Is this what you had in mind?

**Comment by alessandroperilli** [comment]
Yes, this works fine (although I think your outputs are inverted: it seems that the `trigger_words` output is outputting the example prompt and vice versa).

It would be great to not have the opening and closing quotes for each output, but it's a minor issue.

However, and exclusively FYI, I think it's possible to both display and output at the same time. Look for example at the textDebug node in the ttN suite:

<img width="505" alt="Screenshot 2023-12-09 at 12 39 59" src="https://github.com/jitcoder/lora-info/assets/9775949/2c464f81-c6b4-4ef9-a653-56702a930373">

**Comment by jitcoder** [comment]
> Yes, this works fine (although I think your outputs are inverted: it seems that the `trigger_words` output is outputting the example prompt and vice versa).
> 
> However, and exclusively FYI, I think it's possible to both display and output at the same time. Look for example at the textDebug node in the ttN suite:
> 
> <img alt="Screenshot 2023-12-09 at 12 39 59" width="505" src="https://private-user-images.githubusercontent.com/9775949/289272007-2c464f81-c6b4-4ef9-a653-56702a930373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjYwNDksIm5iZiI6MTcwMjEyNTc0OSwicGF0aCI6Ii85Nzc1OTQ5LzI4OTI3MjAwNy0yYzQ2NGY4MS1jNmI0LTRlZjktYTY1My01NjcwMmE5MzAzNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMTI0MjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQ2M2QzNGJiOGU2OWI4YWU5NGViMzc5NjBlOGIzZmJhYzg3YzAxOTRiYTlkMTA2NWVhMjUzNGVjMGMzZDQ1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZSUJlQ7bCn1hi67xRFnMXjlFqC-GOFOh3-rX7N_CXMI">

oh sweet, thx for the info, I'll check it out

**Comment by jitcoder** [comment]
<img width="809" alt="image" src="https://github.com/jitcoder/lora-info/assets/4588694/b12f83f4-c2ad-41f4-9a82-b1fa872f709a">

**Comment by jitcoder** [comment]
addressed: https://github.com/jitcoder/lora-info/commit/db2c5d4df5b438d7efe83d1ccedd88be66b82ad8

**Comment by alessandroperilli** [comment]
Super. It works great!
Thanks for all the time you dedicated to this during your weekend.

UPDATE: 

The node generates the following error for that particular LoRA I flagged in the other issue:

> File "xyz/ComfyUI/execution.py", line 153, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/execution.py", line 83, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/Tools/ComfyUI/execution.py", line 76, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/custom_nodes/lora-info/lora_info.py", line 118, in lora_info
>     (output, triggerWords, examplePrompt, baseModel) = get_lora_info(lora_name)
>                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/custom_nodes/lora-info/lora_info.py", line 64, in get_lora_info
>     trainedWords = ",".join(model_info.get("trainedWords"))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: can only join an iterable

**Comment by jitcoder** [comment]
woops, accidently reintroduced in the refactor. I've fixed in the latest push

**Comment by alessandroperilli** [comment]
Now it works fine, thank you. At this point, you might consider adding your node to the DB list of ComfyUI Manager. So other people who didn't see the Reddit announcement will find it.

**Comment by jitcoder** [comment]
> Now it works fine, thank you. At this point, you might consider adding your node to the DB list of ComfyUI Manager. So other people who didn't see the Reddit announcement will find it.

sweet. yeah I will soon. I'm going to investigate a custom node I saw that reacts to 'input change' without the user having to queue the workflow. I'd like for lora info to execute and show info as soon as the user selects a lora instead of having to hit queue.

I think I'm also going to add another "quality of life" node, like a 'prompt' selector. where the user can just select and use pre made prompts eg. `Universal Negative Prompt`, or `Face Test` that tests a workflow for face detailing accuracy, `Hand Test` or something, it'd be hooked up to github so community members can add/share their prompts.

I've already created a half built node that does this for me.

Will probably end up adding more nodes like this as I build out my workflow.

**Comment by alessandroperilli** [comment]
I've never seen a node that automatically reacts to state changes without queuing the generation, and I've seen hundreds. But if such a node exists and can be done, it would be amazing. 

Re the prompt selector, there are dozens of them. You can find them by searching for "prompt" [on this page](https://ltdrdata.github.io).

I don't like any of them because even if you can see the list of prompt presents from dropdown menus, you never remember exactly what's in each preset. So I ended up creating a very large *visual* prompt builder for the AP Workflow. I prefer to see the full extent of the prompt I'll choose before choosing it.

**Comment by jitcoder** [comment]
> I've never seen a node that automatically reacts to state changes without queuing the generation, and I've seen hundreds. But if such a node exists and can be done, it would be amazing.
> 
> Re the prompt selector, there are dozens of them. You can find them by searching for "prompt" [on this page](https://ltdrdata.github.io).
> 
> I don't like any of them because even if you can see the list of prompt presents from dropdown menus, you never remember exactly what's in each preset. So I ended up creating a very large _visual_ prompt builder for the AP Workflow. I prefer to see the full extent of the prompt I'll choose before choosing it.

done ;)

Now it reacts to user input and updates/displays the output and base model immediately instead of having to queue.

**Comment by jitcoder** [comment]
wrt the prompt selector and given the above update (ie. the ability to update UI elements based on user input), I can probably put together a prompt selector node that shows whats in the preset.

I was also playing around building a workflow and started to feel the need for a "Any Switch". There are some switches in threerg but they are type specific and require a boolean input. I was thinking of a node that acts like a switch with a slider switch instead of requiring an input. 

<img width="411" alt="image" src="https://github.com/jitcoder/lora-info/assets/4588694/834cb7d6-48d9-43d3-a6e5-adb96f6f979f">

so when the switch is "off" it outputs whatever is in `input_a`, and when its "on" it outputs `input_b`

**Comment by alessandroperilli** [comment]
> > I've never seen a node that automatically reacts to state changes without queuing the generation, and I've seen hundreds. But if such a node exists and can be done, it would be amazing.
> > Re the prompt selector, there are dozens of them. You can find them by searching for "prompt" [on this page](https://ltdrdata.github.io).
> > I don't like any of them because even if you can see the list of prompt presents from dropdown menus, you never remember exactly what's in each preset. So I ended up creating a very large _visual_ prompt builder for the AP Workflow. I prefer to see the full extent of the prompt I'll choose before choosing it.
> 
> done ;)
> 
> Now it reacts to user input and updates/displays the output and base model immediately instead of having to queue.

Remarkable. And thank you! 
If this can now read the selected LoRA model from an Efficient Node and a default LoRA Loader checkpoint, as we discussed, it becomes a must have for many, many people.

**Comment by alessandroperilli** [comment]
> wrt the prompt selector and given the above update (ie. the ability to update UI elements based on user input), I can probably put together a prompt selector node that shows whats in the preset.
> 
> I was also playing around building a workflow and started to feel the need for a "Any Switch". There are some switches in threerg but they are type specific and require a boolean input. I was thinking of a node that acts like a switch with a slider switch instead of requiring an input.
> 
> <img alt="image" width="411" src="https://private-user-images.githubusercontent.com/4588694/289470656-834cb7d6-48d9-43d3-a6e5-adb96f6f979f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODc4MjAsIm5iZiI6MTcwMjI4NzUyMCwicGF0aCI6Ii80NTg4Njk0LzI4OTQ3MDY1Ni04MzRjYjdkNi00OGQ5LTQzZDMtYTZlNS1hZGI5NmY2Zjk3OWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMDkzODQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDk4OTdiNTk2ZjljYWZmZGMxOTM0NGJmZGI4MzZjNGE1ZDhkNWM2MzE1YjMzYmQ2MWY4NWEwZGQ3ZmJhMTZhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WipuFCmbwRDtHjHv3df9r3TAT9_6cQAIzWry6veK6F8">
> so when the switch is "off" it outputs whatever is in `input_a`, and when its "on" it outputs `input_b`

Rgthree has a node called `Any Switch` which defaults to the first non-null value. That's my preference over all the other switches I tried so far because it requires no manual reconfiguration.

Also, in the `Impact Pack`, there's a `Switch (Any)`, which allows for infinite input pins and has an embedded selector (no need for a boolean value as input). That is my second most favorite switch.

<img width="470" alt="Screenshot 2023-12-11 at 09 42 57" src="https://github.com/jitcoder/lora-info/assets/9775949/c5f02562-bd83-4d9d-8312-4588dce4e20f">

**Comment by jitcoder** [comment]
> > wrt the prompt selector and given the above update (ie. the ability to update UI elements based on user input), I can probably put together a prompt selector node that shows whats in the preset.
> > I was also playing around building a workflow and started to feel the need for a "Any Switch". There are some switches in threerg but they are type specific and require a boolean input. I was thinking of a node that acts like a switch with a slider switch instead of requiring an input.
> > <img alt="image" width="411" src="https://private-user-images.githubusercontent.com/4588694/289470656-834cb7d6-48d9-43d3-a6e5-adb96f6f979f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODc4MjAsIm5iZiI6MTcwMjI4NzUyMCwicGF0aCI6Ii80NTg4Njk0LzI4OTQ3MDY1Ni04MzRjYjdkNi00OGQ5LTQzZDMtYTZlNS1hZGI5NmY2Zjk3OWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMDkzODQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDk4OTdiNTk2ZjljYWZmZGMxOTM0NGJmZGI4MzZjNGE1ZDhkNWM2MzE1YjMzYmQ2MWY4NWEwZGQ3ZmJhMTZhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WipuFCmbwRDtHjHv3df9r3TAT9_6cQAIzWry6veK6F8">
> > so when the switch is "off" it outputs whatever is in `input_a`, and when its "on" it outputs `input_b`
> 
> Rgthree has a node called `Any Switch` which defaults to the first non-null value. That's my preference over all the other switches I tried so far because it requires no manual reconfiguration.
> 
> Also, in the `Impact Pack`, there's a `Switch (Any)`, which allows for infinite input pins and has an embedded selector (no need for a boolean value as input). That is my second most favorite switch.
> 
> <img alt="Screenshot 2023-12-11 at 09 42 57" width="470" src="https://private-user-images.githubusercontent.com/9775949/289493124-c5f02562-bd83-4d9d-8312-4588dce4e20f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODk1MzksIm5iZiI6MTcwMjI4OTIzOSwicGF0aCI6Ii85Nzc1OTQ5LzI4OTQ5MzEyNC1jNWYwMjU2Mi1iZDgzLTRkOWQtODMxMi00NTg4ZGNlNGUyMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMTAwNzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmE0YWRkYWZjNmUzM2NmOGQ1ZTBmOGMwMzMwNzEyNTA5ZGRlNTY3Mzk3MjVmOTVlOTYxODMyM2EyZGQ5NGJlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u40_6uQmDHmG3tkrv31oJCC5QvKycvUtmvVfKU78m5o">

Ah perfect, thanks!

I've been playing around with trying to get lora_name output a "non-hacky" way with no luck. I think what I'll have to do is give the user an option.
1. Select lora from dropdown
2. Read loras from workspace

if the user selects option 2 then (because there can be multiple different loras in multiple different nodes):
1. Gather all lora_names.
2. Fetch civitai data
3. Show a `selected_index` option
4. display lora data of lora at selected index

**Comment by alessandroperilli** [comment]
Before you try either implementation, I'd suggest you check the code behind this feature:

<img width="913" alt="Screenshot 2023-12-11 at 10 39 58" src="https://github.com/jitcoder/lora-info/assets/9775949/b6d7f1f8-0f45-43bf-8caf-7573a4527b4f">

You summon this popup by right-clicking on stock `Lora Loader` node and selecting `View Info`:

<img width="704" alt="Screenshot 2023-12-11 at 10 40 50" src="https://github.com/jitcoder/lora-info/assets/9775949/cf308c44-e08e-4e75-9f74-7ef899d13edb">

Your implementation is much more useful, IMO, but maybe that code could be useful in this case?

**Comment by jitcoder** [comment]
> Before you try either implementation, I'd suggest you check the code behind this feature:
> 
> <img alt="Screenshot 2023-12-11 at 10 39 58" width="913" src="https://private-user-images.githubusercontent.com/9775949/289509157-b6d7f1f8-0f45-43bf-8caf-7573a4527b4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTE3MDEsIm5iZiI6MTcwMjI5MTQwMSwicGF0aCI6Ii85Nzc1OTQ5LzI4OTUwOTE1Ny1iNmQ3ZjFmOC0wZjQ1LTQzYmYtOGNhZi03NTczYTQ1MjdiNGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMTA0MzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWJmNThmYWVkM2M4NDJlNzVjODQ5ZmJiODJiOTBlMWY1OWNlNmJkZWQ4ODM2M2Y0NGRlZGE5NTUwYzYxZmE4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3JeZHmh-_XZ43tUsjv_NbeOPg1wiLJKFros24vSL6mE">
> You summon this popup by right-clicking on stock `Lora Loader` node and selecting `View Info`:
> 
> <img alt="Screenshot 2023-12-11 at 10 40 50" width="704" src="https://private-user-images.githubusercontent.com/9775949/289509474-cf308c44-e08e-4e75-9f74-7ef899d13edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTE3MDEsIm5iZiI6MTcwMjI5MTQwMSwicGF0aCI6Ii85Nzc1OTQ5LzI4OTUwOTQ3NC1jZjMwOGM0NC1lMDhlLTRlNzUtOWY3NC03ZWY4OTlkMTNlZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMTA0MzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGU1M2IzOWRlNDA4Y2E0YThhMWVkY2MwZjcwZDdlZTM5MGNkZDY5MWU5MzZlNmQ0MmE4MWQ1Y2Y5Mzg0ZjNiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ca96-OpfhTdYiQYTNvqfmveEUy83uKdnoVkfNooeqNs">
> Your implementation is much more useful, IMO, but maybe that code could be useful in this case?

where is this node from? None of the loaders I have show that context menu option.

<img width="367" alt="image" src="https://github.com/jitcoder/lora-info/assets/4588694/abd332db-757a-4c31-914c-8afac596a1af">

**Comment by alessandroperilli** [comment]
It's not a property of any specific node, but a capability that applies to the stock ComfyUI `LoraLoader` node when you install the [Custom Scripts suite](https://github.com/pythongosssss/ComfyUI-Custom-Scripts).
