### ISSUE TITLE
[FEATURE REQUEST] Inclusion in ComfyUI Manager database

### ISSUE THREAD

**Issue by alessandroperilli** [jitcoder/lora-info#4]
I've added this node to the newly released [AP Workflow 7.0](https://perilli.com/ai/comfyui/), but users are struggling because it's the only node that they cannot install via the ComfyUI Manager.

If you could submit a PR to their repo, it would be much easier for people to find and install this great node.

**Comment by jitcoder** [comment]
https://github.com/ltdrdata/ComfyUI-Manager/pull/258

**Comment by alessandroperilli** [comment]
That's great, thank you!
