### ISSUE TITLE
db.json file not found, comfyui error

### ISSUE THREAD

**Issue by tro2789** [jitcoder/lora-info#6]
I have the repository installed via ComfyUI Manager, and whenever I load a workflow that uses nodes from this repo I get the following error:

![image](https://github.com/jitcoder/lora-info/assets/2295504/cacd3c97-78a8-476e-9eac-5ce3f1af4706)

Any idea how I might fix this?

**Comment by jitcoder** [comment]
Hello, I believe this issue was resolved a while ago and I forgot to close the ticket. if the issue is still present please feel free to reopen the issue
