### ISSUE TITLE
Won't update list of LORAs

### ISSUE THREAD

**Issue by vicentecarro** [jitcoder/lora-info#8]
After installing some LORAs using the Workspace Manager custom node (https://github.com/11cafe/comfyui-workspace-manager), that allows to install models on the fly; and pushing Refresh; and manually refresh the page in the browser, Lora Info still won't show me the new LORAs, while everything else in comfyUI do acknoledge the new LORAs.
Maybe LORA info is making a "hard-coded" list of loras at startup and never updates it again until the server(comfyui) is restarted?

**Comment by jitcoder** [comment]
should be resolved by @royceschultz 's PR
