### ISSUE TITLE
Adding the "source" node

### ISSUE THREAD

**Issue by rbs250** [jitcoder/lora-info#9]
Hi! thanks for this cool node! very useful!
I'm trying to set it up like in the main example but not sure how to add the "source" node where the text is being shown. how can I add it?

**Comment by secretivebanana** [comment]
Hey.
I had the same issue. It seems that the "source" node is from [rgthree](https://github.com/rgthree/rgthree-comfy).<br> Within ComfyUI (after rgthree is installed) the node is named "Display Any (Rgthree)". 
Also for anyone interested, there is another custom node named [Lora Auto Trigger Words](https://github.com/idrirap/ComfyUI-Lora-Auto-Trigger-Words) which has similar features to this one.
